version: '3.8'

services:
  solace:
    image: solace/solace-pubsub-standard:latest
    container_name: solace-broker
    ports:
      - "8080:8080"    # Web management console
      - "55555:55555"  # SMF (Messaging)
      - "8008:8008"    # REST
      - "1883:1883"    # MQTT
      - "5672:5672"    # AMQP
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
      - service_semp_enable=1
    shm_size: 2g
    ulimits:
      nofile:
        soft: 2448
        hard: 1048576
    volumes:
      - solace_data:/var/lib/solace
    restart: unless-stopped

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-free
    environment:
      - ORACLE_PWD=Admin123
      - ORACLE_SID=FREE
    ports:
      - "1521:1521"   # SQL*Net (Oracle DB)
      - "5500:5500"   # EM Express
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped
  solace-pubsub-connector-debezium:
    image: solace/solace-pubsub-connector-debezium:3.0.3
    container_name: solace-pubsub-connector-debezium
    depends_on:
      - solace-broker
      - oracle-free
    environment:
      SOLACE_JAVA_HOST: ${SOLACE_JAVA_HOST:-host.docker.internal:55555}
      # Create a read-only user for the healthcheck
      # Note: This will override all users defined in config files.
      SOLACE_CONNECTOR_SECURITY_USERS_0_NAME: ${HEALTHCHECK_USER_NAME:?HEALTHCHECK_USER_NAME must be set}
      SOLACE_CONNECTOR_SECURITY_USERS_0_PASSWORD: ${HEALTHCHECK_USER_PASSWORD:?HEALTHCHECK_USER_PASSWORD must be set}
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://${HEALTHCHECK_USER_NAME}:${HEALTHCHECK_USER_PASSWORD}@localhost:8090/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    ports:
      - '8090:8090'
    volumes:
      - type: bind
        source: /home/ec2-user/git/hibank-demo/libs/
        target: /app/external/libs/
        read_only: true
      - type: bind
        source: /home/ec2-user/git/hibank-demo/config/
        target: /app/external/spring/config/
        read_only: true
    restart: unless-stopped
volumes:
  solace_data:
  oracle_data:
